# Generated by Django 3.0.6 on 2020-05-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api1_nextdays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='weatherAPIForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=25)),
                ('cAdress', models.CharField(max_length=25)),
                ('cKey', models.CharField(max_length=25)),
                ('iCallsPerDay', models.PositiveIntegerField()),
                ('iMaxCallsPerday', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='weatherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iMax', models.DecimalField(decimal_places=1, max_digits=3)),
                ('iMin', models.DecimalField(decimal_places=1, max_digits=3)),
                ('iAvg', models.DecimalField(decimal_places=1, max_digits=3)),
                ('iProbability', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cUnit', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='cCountry',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='cLatitude',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='cLongitude',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='iPostCode',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='weatherDayForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dForecasteDate', models.DateTimeField()),
                ('dCallDate', models.DateTimeField()),
                ('cName', models.CharField(max_length=25)),
                ('mAPI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api1_nextdays.weatherAPIForecast')),
                ('mHourSun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunDetail', to='weather_api1_nextdays.weatherDetail')),
                ('mRain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rainDetail', to='weather_api1_nextdays.weatherDetail')),
                ('mTemp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tempDetail', to='weather_api1_nextdays.weatherDetail')),
                ('mWind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='windDetail', to='weather_api1_nextdays.weatherDetail')),
            ],
        ),
    ]
