# Generated by Django 3.0.6 on 2020-05-19 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api1_nextdays', '0002_auto_20200519_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdayforecast',
            name='cIcon',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
