# Generated by Django 3.0.6 on 2020-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api1_nextdays', '0003_weatherdayforecast_cicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherapiforecast',
            name='cAdress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherapiforecast',
            name='cKey',
            field=models.CharField(max_length=50),
        ),
    ]
